<?php
/**
* ┌────────────────────────────────────────────────────────────
* │                         MPF - VIEW
* ├────────────────────────────────────────────────────────────
* │ 📌 Desc      : Autogenerated view (modernized UI)
* │ 👨 Author    : Adão Major (adaomajor)
* │ 🐱‍👤 GitHub  : https://github.com/adaomajor
* │ 🔄 Version   : 1.1.0
* │ 🧱 Framework : MPF Framework
* └────────────────────────────────────────────────────────────
*/
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MPF · Welcome</title>

    <style>
        :root {
            --bg-1: #0f0c29;
            --bg-2: #302b63;
            --bg-3: #24243e;
            --accent: #8b5cf6;
            --text: #e5e7eb;
            --muted: #9ca3af;
        }

        * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            min-height: 100vh;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            color: var(--text);
            background: linear-gradient(135deg, var(--bg-1), var(--bg-2), var(--bg-3));
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
        }

        /* Decorative background icon */
        .back-banner {
            position: absolute;
            font-size: 22rem;
            opacity: 0.06;
            animation: float 6s ease-in-out infinite;
            user-select: none;
        }

        @keyframes float {
            0%   { transform: translateY(0); }
            50%  { transform: translateY(-20px); }
            100% { transform: translateY(0); }
        }

        /* Glass container */
        .card {
            width: min(92%, 460px);
            padding: 2.8rem 2.2rem;
            text-align: center;
            background: rgba(255, 255, 255, 0.08);
            backdrop-filter: blur(14px);
            border-radius: 20px;
            border: 1px solid rgba(255, 255, 255, 0.12);
            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.45);
            z-index: 1;
        }

        h1 {
            margin: 0;
            font-size: 2.6rem;
            letter-spacing: 0.12em;
        }

        .subtitle {
            margin-top: 0.4rem;
            font-size: 0.9rem;
            letter-spacing: 0.14em;
            color: var(--muted);
        }

        .author {
            margin: 1.4rem 0;
            padding-bottom: 1.2rem;
            font-size: 0.85rem;
            border-bottom: 1px solid rgba(255, 255, 255, 0.2);
            color: var(--muted);
        }

        h2 {
            margin: 1.6rem 0 0.8rem;
            font-size: 2rem;
            font-weight: 700;
            color: var(--accent);
        }

        p {
            margin: 0 0 2rem;
            color: var(--muted);
            font-size: 0.95rem;
        }

        a.button {
            display: inline-block;
            padding: 0.85rem 1.8rem;
            border-radius: 999px;
            text-decoration: none;
            font-weight: 600;
            letter-spacing: 0.08em;
            color: #ffffff;
            background: linear-gradient(135deg, #8b5cf6, #6366f1);
            box-shadow: 0 12px 28px rgba(139, 92, 246, 0.45);
            transition: transform 0.2s ease, box-shadow 0.2s ease;
        }

        a.button:hover {
            transform: translateY(-2px);
            box-shadow: 0 18px 38px rgba(139, 92, 246, 0.65);
        }
    </style>
</head>
<body>

    <div class="back-banner">🚀</div>

    <div class="card">
        <h1>MPF</h1>
        <div class="subtitle">MINIMALIST PHP FRAMEWORK</div>

        <div class="author">made by · adaomajor</div>

        <h2>Welcome to MPF</h2>
        <p>Build fast, clean, and minimal PHP applications.</p>

        <a class="button" href="https://adaomajor.github.io">LEARN MORE</a>
    </div>

</body>
</html>
